### ISSUE TITLE
required_approval_count not working as documented

### ISSUE THREAD

**Issue by KissPeter** [adRise/update-pr-branch#19]
This is in the docs:
_The action will skip PRs that have less approvals than required_approval_count._

however I'm getting:

```
Won't update #625, the reason:
      > approvalsCount: 1, requiredApprovalCount: 0, changesRequestedReviews: 1
```

**Comment by zhiyelee** [comment]
@KissPeter sorry for the late response. According to the reason message, one of the reviewers gave `request for change` for the PR. Based on the current logic, we will skip the PR because this PR is not in the ready to merge state
