### ISSUE TITLE
Require auto merge enabled is not working as documented

### ISSUE THREAD

**Issue by mariushusevaag** [adRise/update-pr-branch#20]
I'm getting the following error: `Invalid action input 'require_auto_merge_enabled'`
I can see from the PR enabling `require_auto_merge_enable` that it's not including the right input for auto merge enable.
`require_auto_merge_anable` should be defined as an input in this file:
![image](https://github.com/adRise/update-pr-branch/assets/19565557/8b7e6a87-1981-43d0-8635-4ef5d86ffb2f)

If allowed, I could contribute to fix the issue.

**Comment by zhiyelee** [comment]
@mariushusevaag Sorry, just saw this. Sure contribution is very welcome

**Comment by zhiyelee** [comment]
Hi @mariushusevaag I have fixed the issue and released a new version[ v0.7.1](https://github.com/adRise/update-pr-branch/releases/tag/v0.7.1). Let me know if the issue is still there. Thank you again for the report
